import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Users, ShieldAlert, LogOut, UserCircle, ShieldCheck, Trash2, Activity, Globe, Download, TrendingUp } from 'lucide-react';
import toast from 'react-hot-toast';
import API from '../api';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Line } from 'react-chartjs-2';
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
  Filler
} from 'chart.js';

ChartJS.register(CategoryScale, LinearScale, PointElement, LineElement, Title, Tooltip, Legend, Filler);

const Dashboard = () => {
  const navigate = useNavigate();
  const [userData, setUserData] = useState(null);
  const [allUsers, setAllUsers] = useState([]);
  const [logs, setLogs] = useState([]);
  const [stats, setStats] = useState({ totalLogs: 0, failedAttempts: 0 });
  const [loading, setLoading] = useState(true);
  const [chartData, setChartData] = useState(null);

  const handleLogout = (showToast = true) => {
    localStorage.removeItem('token');
    if (showToast) {
      toast.success('System Terminated Successfully');
    }
    navigate('/login');
  };

  const downloadPDFReport = () => {
    try {
      const doc = new jsPDF();
      
      doc.setFillColor(15, 23, 42);
      doc.rect(0, 0, 210, 40, 'F');
      
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(22);
      doc.text("SECURITY AUDIT REPORT", 14, 25);
      
      doc.setTextColor(148, 163, 184);
      doc.setFontSize(10);
      doc.text(`Generated by: ${userData?.username || 'Admin'} | Status: Encrypted`, 14, 48);
      doc.text(`Date: ${new Date().toLocaleString()}`, 14, 53);

      const tableRows = logs.map(log => [
        new Date(log.timestamp).toLocaleString(),
        log.action,
        log.ipAddress || '127.0.0.1',
        log.status.toUpperCase()
      ]);

      autoTable(doc, {
        startY: 60,
        head: [['Timestamp', 'Action', 'Origin IP', 'Status']],
        body: tableRows,
        theme: 'grid',
        headStyles: { fillColor: [6, 182, 212], textColor: 255, fontStyle: 'bold' },
        styles: { fontSize: 8, cellPadding: 3 },
        alternateRowStyles: { fillColor: [248, 250, 252] }
      });

      doc.save(`Audit_Report_${Date.now()}.pdf`);
      toast.success("Audit Report Exported Successfully");
    } catch (error) {
      console.error("PDF Generation Error:", error);
      toast.error("Failed to generate PDF report");
    }
  };

  const fetchDashboardData = async () => {
    try {
      const token = localStorage.getItem('token');
      if (!token) {
        handleLogout(false);
        return;
      }

      const res = await API.get('/api/user/profile', {
        headers: { Authorization: `Bearer ${token}` }
      });
      setUserData(res.data);

      if (res.data.role === 'Admin') {
        const [usersRes, logsRes, statsRes] = await Promise.all([
          API.get('/api/user/', {
            headers: { Authorization: `Bearer ${token}` }
          }),
          API.get('/api/logs', {
            headers: { Authorization: `Bearer ${token}` }
          }),
          API.get('/api/logs/stats', {
            headers: { Authorization: `Bearer ${token}` }
          })
        ]);
        
        if (statsRes.data.failedAttempts > stats.failedAttempts) {
          toast.error("UNAUTHORIZED ACCESS DETECTED!", {
            duration: 4000,
            icon: '🚨',
            style: { background: '#991b1b', color: '#fff', fontWeight: 'bold' }
          });
        }

        setAllUsers(usersRes.data);
        setLogs(logsRes.data);
        setStats(statsRes.data);
      }
      setLoading(false);
    } catch (err) {
      if (err.response?.status === 401 || err.response?.status === 403) {
        toast.error("Session Expired");
        handleLogout(false);
      } else {
        toast.error("Security Fetch Error");
        setLoading(false);
      }
    }
  };

  useEffect(() => {
    fetchDashboardData();
    const interval = setInterval(fetchDashboardData, 10000);
    return () => clearInterval(interval);
  }, [stats.failedAttempts]);

  useEffect(() => {
    if (logs.length > 0) {
      const last10Logs = [...logs].slice(0, 10).reverse();
      setChartData({
        labels: last10Logs.map(l => new Date(l.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })),
        datasets: [{
          label: 'Security Events',
          data: last10Logs.map(l => l.status === 'Success' ? 5 : 20),
          fill: true,
          borderColor: '#06b6d4',
          backgroundColor: 'rgba(6, 182, 212, 0.1)',
          tension: 0.4,
          pointRadius: 4,
          pointBackgroundColor: '#06b6d4'
        }]
      });
    }
  }, [logs]);

  const handleDeleteUser = async (id) => {
    if (window.confirm("Terminate this user node?")) {
      try {
        const token = localStorage.getItem('token');
        await API.delete(`/api/user/${id}`, {
          headers: { Authorization: `Bearer ${token}` }
        });
        toast.success("User Node Terminated");
        fetchDashboardData();
      } catch (err) {
        toast.error("Deletion Failed");
      }
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-slate-950 flex flex-col items-center justify-center">
        <div className="w-16 h-16 border-4 border-cyan-500/20 border-t-cyan-500 rounded-full animate-spin"></div>
        <p className="text-cyan-500 mt-4 font-mono tracking-widest animate-pulse uppercase">Syncing Security Layers...</p>
      </div>
    );
  }

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-10">
        <div>
          <h1 className="text-4xl font-extrabold text-white flex items-center gap-3">
            <ShieldCheck className="text-cyan-400" size={36} />
            System <span className="text-cyan-400">Control</span>
          </h1>
          <p className="text-slate-400 mt-2">
            Operator: <span className="text-white font-bold uppercase">{userData?.username}</span> | 
            Protocol: <span className="text-green-400 font-mono">ACTIVE-ENCRYPTION</span>
          </p>
        </div>
        
        <button 
          onClick={() => handleLogout(true)} 
          className="flex items-center gap-2 bg-red-500/10 hover:bg-red-500/20 text-red-400 px-6 py-3 rounded-xl border border-red-500/30 transition-all font-bold tracking-widest uppercase text-xs"
        >
          <LogOut size={18} /> Terminate Session
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-8">
        <div className="bg-white/5 backdrop-blur-xl border border-white/10 p-6 rounded-3xl">
          <div className="flex items-center gap-4 mb-4">
            <div className="p-3 bg-cyan-500/20 rounded-2xl text-cyan-400"><UserCircle /></div>
            <h3 className="text-lg font-bold text-white uppercase tracking-tighter">Identity Node</h3>
          </div>
          <p className="text-slate-400">Security Clearance: <span className="text-cyan-400 font-mono font-bold uppercase">{userData?.role}</span></p>
        </div>

        {userData?.role === 'Admin' && (
          <div className="bg-white/5 backdrop-blur-xl border border-white/10 p-6 rounded-3xl border-purple-500/30">
            <div className="flex items-center gap-4 mb-4">
              <div className="p-3 bg-purple-500/20 rounded-2xl text-purple-400"><Users /></div>
              <h3 className="text-lg font-bold text-white uppercase tracking-tighter">Network Nodes</h3>
            </div>
            <p className="text-slate-400">Authorized Personnel: <span className="text-purple-400 font-bold">{allUsers.length} Users</span></p>
          </div>
        )}

        <div className={`bg-white/5 backdrop-blur-xl border p-6 rounded-3xl transition-all duration-500 relative overflow-hidden ${stats.failedAttempts > 0 ? 'border-red-500/50 shadow-[0_0_15px_rgba(239,68,68,0.1)]' : 'border-orange-500/30'}`}>
          <div className="flex items-center gap-4 mb-4">
            <div className={`p-3 rounded-2xl ${stats.failedAttempts > 0 ? 'bg-red-500/20 text-red-400' : 'bg-orange-500/20 text-orange-400'}`}>
              <ShieldAlert className={stats.failedAttempts > 0 ? 'animate-pulse' : ''} />
            </div>
            <h3 className="text-lg font-bold text-white uppercase tracking-tighter">System Health</h3>
          </div>
          <p className="text-slate-400 flex justify-between items-center">
            Threat Alerts: 
            <span className={`font-bold ${stats.failedAttempts > 0 ? 'text-red-500' : 'text-green-400'}`}>
              {stats.failedAttempts}
            </span>
          </p>
          <div className="flex justify-between items-center mt-1">
            <p className="text-[10px] text-slate-500 uppercase tracking-widest">Traffic Logs: {stats.totalLogs}</p>
            {stats.failedAttempts > 0 && <span className="text-[8px] bg-red-500 text-white px-1 rounded animate-bounce">CRITICAL</span>}
          </div>
        </div>
      </div>

      <div className="bg-slate-900/50 border border-white/5 rounded-3xl p-8 mb-8">
        <h2 className="text-xl font-bold text-white mb-6 uppercase tracking-widest border-l-4 border-cyan-500 pl-4 flex items-center gap-2">
          <TrendingUp size={20} className="text-cyan-400" /> Activity Trend Analysis
        </h2>
        <div className="h-[250px] w-full">
          {chartData ? <Line data={chartData} options={{ responsive: true, maintainAspectRatio: false, plugins: { legend: { display: false } }, scales: { y: { grid: { color: 'rgba(255,255,255,0.05)' }, ticks: { color: '#64748b' } }, x: { grid: { display: false }, ticks: { color: '#64748b' } } } }} /> : <p className="text-slate-500 text-center font-mono py-10 tracking-widest animate-pulse">COLLECTING ACTIVITY METRICS...</p>}
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="bg-slate-900/50 border border-white/5 rounded-3xl p-8 overflow-hidden">
          <h2 className="text-xl font-bold text-white mb-6 uppercase tracking-widest border-l-4 border-cyan-500 pl-4">Personnel Database</h2>
          {userData?.role === 'Admin' ? (
            <div className="overflow-x-auto">
              <table className="w-full text-left border-collapse">
                <thead>
                  <tr className="border-b border-white/10 text-slate-500 text-xs uppercase tracking-widest">
                    <th className="py-4 px-2">Identifier</th>
                    <th className="py-4 px-2">Clearance</th>
                    <th className="py-4 px-2 text-right">Action</th>
                  </tr>
                </thead>
                <tbody className="text-slate-300">
                  {allUsers.map((u) => (
                    <tr key={u._id} className="border-b border-white/5 hover:bg-white/5 transition-colors group">
                      <td className="py-4 px-2">
                        <p className="font-mono text-cyan-400 text-sm">{u.username}</p>
                        <p className="text-[10px] text-slate-500">{u.email}</p>
                      </td>
                      <td className="py-4 px-2 text-[10px] font-bold">
                        <span className={`px-2 py-1 rounded-md ${u.role === 'Admin' ? 'bg-purple-500/10 text-purple-400' : 'bg-slate-500/10 text-slate-400'}`}>
                          {u.role.toUpperCase()}
                        </span>
                      </td>
                      <td className="py-4 px-2 text-right">
                        {u._id !== userData._id && (
                          <button onClick={() => handleDeleteUser(u._id)} className="p-2 text-slate-500 hover:text-red-500 transition-colors">
                            <Trash2 size={16} />
                          </button>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ) : (
            <div className="h-48 flex items-center justify-center border border-dashed border-red-500/20 rounded-2xl bg-red-500/5">
              <p className="text-red-400 font-mono text-xs uppercase tracking-widest">Access Denied: Admin Level Required</p>
            </div>
          )}
        </div>

        <div className="bg-slate-900/50 border border-white/5 rounded-3xl p-8 overflow-hidden">
          <div className="flex justify-between items-center mb-6">
            <h2 className="text-xl font-bold text-white uppercase tracking-widest border-l-4 border-orange-500 pl-4 flex items-center gap-2">
              <Activity size={20} className="text-orange-400" /> Security Audit
            </h2>
            {userData?.role === 'Admin' && (
              <button 
                onClick={downloadPDFReport}
                className="flex items-center gap-2 text-[10px] bg-cyan-500/10 hover:bg-cyan-500/20 text-cyan-400 border border-cyan-500/30 px-3 py-1.5 rounded-lg transition-all font-bold uppercase tracking-widest"
              >
                <Download size={12} /> Export PDF
              </button>
            )}
          </div>
          {userData?.role === 'Admin' ? (
            <div className="space-y-4 max-h-[400px] overflow-y-auto pr-2 custom-scrollbar">
              {logs.map((log) => (
                <div key={log._id} className={`p-3 bg-white/5 rounded-xl border flex justify-between items-center group transition-all ${log.status === 'Success' ? 'border-white/5 hover:border-cyan-500/30' : 'border-red-500/20 hover:border-red-500/50'}`}>
                  <div>
                    <p className={`text-sm font-mono ${log.status === 'Success' ? 'text-slate-200' : 'text-red-400'}`}>{log.action}</p>
                    <div className="flex items-center gap-3 mt-1">
                      <p className="text-[10px] text-slate-500">{new Date(log.timestamp).toLocaleTimeString()}</p>
                      <span className="flex items-center gap-1 text-[10px] text-cyan-500/70 font-mono">
                        <Globe size={10} /> {log.ipAddress || 'Internal'}
                      </span>
                    </div>
                  </div>
                  <span className={`text-[9px] font-black px-2 py-1 rounded shadow-sm ${log.status === 'Success' ? 'bg-green-500/10 text-green-400 border border-green-500/20' : 'bg-red-500/10 text-red-400 border border-red-500/20'}`}>
                    {log.status.toUpperCase()}
                  </span>
                </div>
              ))}
            </div>
          ) : (
            <div className="h-48 flex items-center justify-center border border-dashed border-red-500/20 rounded-2xl bg-red-500/5">
              <p className="text-red-400 font-mono text-xs uppercase tracking-widest">Logs Encrypted: Unauthorized Access</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default Dashboard;