POST http://localhost:5001/api/auth/register
Content-Type: application/json

{
  "username": "ankit_vit_6",
  "email": "ankit_test6@vit.ac.in",
  "password": "AnkitPassword123",
  "role": "Admin"
}
### Login Request
POST http://localhost:5001/api/auth/login
Content-Type: application/json

{
  "email": "ankit_test6@vit.ac.in",
  "password": "NewSecurePassword123"
}
### Protected Test Route
GET http://localhost:5001/api/user/test
token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OWRmMGI3MzJiZDk2OTIwYmVhMTBhZCIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTc3MTk2MDY5NCwiZXhwIjoxNzcxOTY0Mjk0fQ.71aLHzejkE6_WFX7Q0gflUlluWAPXrG2_MVLVz4P0iA
### Admin Dashboard Test
GET http://localhost:5001/api/user/admin-dashboard
token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OWRmMGI3MzJiZDk2OTIwYmVhMTBhZCIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTc3MTk2MDY5NCwiZXhwIjoxNzcxOTY0Mjk0fQ.71aLHzejkE6_WFX7Q0gflUlluWAPXrG2_MVLVz4P0iA
### Profile Access Test
GET http://localhost:5001/api/user/profile/699df0b732bd96920bea10ad
token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OWRmMGI3MzJiZDk2OTIwYmVhMTBhZCIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTc3MTk2MDY5NCwiZXhwIjoxNzcxOTY0Mjk0fQ.71aLHzejkE6_WFX7Q0gflUlluWAPXrG2_MVLVz4P0iA
###Normal User Testing
POST http://localhost:5001/api/auth/register
Content-Type: application/json

{
  "username": "normal_user_ankit",
  "email": "normal@vit.ac.in",
  "password": "UserPassword123",
  "role": "User" 
}
###Login Test
POST http://localhost:5001/api/auth/login
Content-Type: application/json

{
  "email": "normal@vit.ac.in",
  "password": "UserPassword123"
}
### Attempt admin access check
GET http://localhost:5001/api/user/admin-dashboard
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OWRmZTkwNWIwNTI4ZmJlNDk3MjM2MSIsInJvbGUiOiJVc2VyIiwiaWF0IjoxNzcxOTYyMDI2LCJleHAiOjE3NzE5NjU2MjZ9.9i5VfMnFCtVbybilGHb8TTdNlmQRKsMqJrqZMBvorkY
### Delete User (Admin Only)
DELETE http://localhost:5001/api/user/699dfe905b0528fbe4972361
token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OWRmMGI3MzJiZDk2OTIwYmVhMTBhZCIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTc3MTk2MjQ2NSwiZXhwIjoxNzcxOTY2MDY1fQ.7QXrQVAF9l2ZKPHgpocQKfMqWRdv_jm6TDIZ6o_zvQU
### Update User
PUT http://localhost:5001/api/user/699df0b732bd96920bea10ad
Content-Type: application/json
token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OWRmMGI3MzJiZDk2OTIwYmVhMTBhZCIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTc3MTk2MzE3MCwiZXhwIjoxNzcxOTY2NzcwfQ.pIn_OsVI-CbNhzF2_SPdnGwnZMCrRL04l7AgH_oHW0U

{
  "username": "Ankit_Pro_Coder",
  "password": "NewSecurePassword123"
}
### Get All Users Professional
GET http://localhost:5001/api/user/
token: Bearer PASTE_YOUR_ADMIN_TOKEN_HERE